### ISSUE TITLE
Need intro paragraph

### ISSUE THREAD

**Issue by lskatz** [microbinfie-hackathon2020/CSIS#27]
If some bugs are found with our unit testing, can we have some boilerplate language so that we can explain the hackathon in external issues pages?  For example, if a bug is found in `biotool`, can one of us go to the `biotool` github site, file an issue, and explain where we are coming from?

Thanks @crashfrog for suggesting this.

**Comment by lskatz** [comment]
Hi,  
I hope this message finds you well.  I am participating in a project [CSIS](https://github.com/microbinfie-hackathon2020/CSIS) where we perform testing of bioinformatics software and report whether it works on our GitHub repo.  
I created this test for your software.  Over time, I hope that this helps your software become more sustainable and that it helps highlight your software as such.  Could I send you a pull request to include it in your software?

@crashfrog or others could you look over and revise this message?

**Comment by lskatz** [comment]
@crashfrog @boasvdp @luispedro @pvanheus @rpetit3 @aineniamh @ay-amityadav @cimendes @viralverity @bmtalbot

Tagging some people from the conference to weigh in on this language (I know this list of people is not exhaustive).  Thank you if you can comment; no problem if you cannot.

**Comment by cimendes** [comment]
Are we including this message in the PR or is it a pre-PR message? In case of the first I would word it a bit more proactively (is this even a word?). Here's my suggestion..

> Hi,
> I hope this message finds you well. I am participating in the [CSIS project](https://github.com/microbinfie-hackathon2020/CSIS) where we perform [blackbox testing](https://www.softwaretestinghelp.com/black-box-testing/) of bioinformatics software,  based on the requirements and functionality of a tool integrated with [Github actions](https://github.com/features/actions), and report whether it works on our GitHub repo. You can see some examples [here](https://github.com/microbinfie-hackathon2020/CSIS#current-software).
> I created this test (link goes here) for your software. Over time, I hope that this helps your software become more sustainable and that it helps highlight your software as such. If you're interested I would be glad to send you a pull request to be included it in your software. I'm also very interested in any feedback you might be able to provide for this project.

**Comment by crashfrog** [comment]
I might further expand on the purpose and background of CSIS:

> Hi,

> I hope this message finds you well. My name is ______ and I'm a participant in the 2020 Microbial Bioinformatics CSIS Hackathon, an effort to expand the use of automated blackbox testing in bioinformatics consistent with [T. Seeman's "10 Recommendations for creating usable bioinformatics command line software."](https://doi.org/10.1186/2047-217X-2-15) As part of this effort we've configured a GitHub Action to install and run your tool in an isolated test environment in response to new commits and we now submit this configuration to your repository as a pull request.

> We hope you'll review this PR and find it a useful and helpful addition to your project. Tools participating in the CSIS testing effort can have a badge displayed at the CSIS project repository (https://github.com/microbinfie-hackathon2020/CSIS) or even add our own CSIS badge to your project's README to display the current status of the test.

That last part I just made up but it's [apparently something we could do](https://github.com/badges/shields), maybe - create a custom CSIS badge that repo owners could add that reflects the pass/fail status of the tests we contribute. "CSIS approved!" Or maybe pass is @lskatz smiling and fail is @cimendes frowning?

**Comment by cimendes** [comment]
LOL @crashfrog !!!!

**Comment by luispedro** [comment]
My suggestion is to just open a PR instead of a pre-PR message and start with the issues related to that project before mentioning the context (CSIS).

I suggest the templates below

**If there is an actual bug**

1. Open an issue with the bug report

> EXPLAIN THE ACTUAL ISSUE (_e.g._, `biosoftware` will crash if non-canonical amino acids are found)
>
> I am participating in a project (CSIS) where we perform testing of bioinformatics software and report whether it works on our [GitHub repo](https://github.com/microbinfie-hackathon2020/CSIS).
> Over time, we hope that this helps software become more sustainable and that it helps highlight your software as such.
>
> I created a test for your software and found the above issue.
>
> I will also create a separate pull request to include the tests into your repository if you find them useful.

2. Then directly open a pull request with the test:

> This pull request adds testing to SOFTWARE. In particular, it tests (1) .... (2) ... (3) .... .
>
> As mentioned in ISSUE [LINK TO THE PREVIOUS ISSUE], I/we created tests in an effort to improve quality and sustainability as part of the [CSIS](https://github.com/microbinfie-hackathon2020/CSIS) project.
>
> I hope you find the tests useful, and I am happy to incorporate feedback into it.

**If there is no bug**, you can still contribute the tests:

> This pull request adds testing to SOFTWARE. In particular, it tests (1) .... (2) ... (3) .... .
>
> I am participating in a project (CSIS) where we perform testing of bioinformatics software and report whether it works on our [GitHub repo](https://github.com/microbinfie-hackathon2020/CSIS).
> Over time, we hope that this helps software become more sustainable and that it helps highlight your software as such.
>
> I created a test for your software. I hope you find it useful, but am happy to incorporate feedback into it.

**Comment by lskatz** [comment]
LOL @crashfrog !  I do like this revised Issues message
> I hope this message finds you well. My name is ______ and I'm a participant in the 2020 Microbial Bioinformatics CSIS Hackathon, an effort to expand the use of automated blackbox testing in bioinformatics consistent with T. Seeman's "10 Recommendations for creating usable bioinformatics command line software." As part of this effort we've configured a GitHub Action to install and run your tool in an isolated test environment in response to new commits and we now submit this configuration to your repository as a pull request.
>We hope you'll review this PR and find it a useful and helpful addition to your project. Tools participating in the CSIS testing effort can have a badge displayed at the CSIS project repository (https://github.com/microbinfie-hackathon2020/CSIS) or even add our own CSIS badge to your project's README to display the current status of the test.

@luispedro I like the idea of having a PR and I think I'll make a separate conversation about that.
