### ISSUE TITLE
PR template

### ISSUE THREAD

**Issue by lskatz** [microbinfie-hackathon2020/CSIS#39]
Per the conversation in #27, if someone makes a pull request to a target repo, how would we recommend the language?

**Comment by lskatz** [comment]
Copying and pasting @luispedro 's text below:

My suggestion is to just open a PR instead of a pre-PR message and start with the issues related to that project before mentioning the context (CSIS).

I suggest the templates below

**If there is an actual bug**

1. Open an issue with the bug report

> EXPLAIN THE ACTUAL ISSUE (_e.g._, `biosoftware` will crash if non-canonical amino acids are found)
>
> I am participating in a project (CSIS) where we perform testing of bioinformatics software and report whether it works on our [GitHub repo](https://github.com/microbinfie-hackathon2020/CSIS).
> Over time, we hope that this helps software become more sustainable and that it helps highlight your software as such.
>
> I created a test for your software and found the above issue.
>
> I will also create a separate pull request to include the tests into your repository if you find them useful.

2. Then directly open a pull request with the test:

> This pull request adds testing to SOFTWARE. In particular, it tests (1) .... (2) ... (3) .... .
>
> As mentioned in ISSUE [LINK TO THE PREVIOUS ISSUE], I/we created tests in an effort to improve quality and sustainability as part of the [CSIS](https://github.com/microbinfie-hackathon2020/CSIS) project.
>
> I hope you find the tests useful, and I am happy to incorporate feedback into it.

**If there is no bug**, you can still contribute the tests:

> This pull request adds testing to SOFTWARE. In particular, it tests (1) .... (2) ... (3) .... .
>
> I am participating in a project (CSIS) where we perform testing of bioinformatics software and report whether it works on our [GitHub repo](https://github.com/microbinfie-hackathon2020/CSIS).
> Over time, we hope that this helps software become more sustainable and that it helps highlight your software as such.
>
> I created a test for your software. I hope you find it useful, but am happy to incorporate feedback into it.

**Comment by cimendes** [comment]
Done here! https://github.com/microbinfie-hackathon2020/CSIS/tree/main/templates
