### ISSUE TITLE
Where should edits to markdown files go? (dev, main, or new patch)

### ISSUE THREAD

**Issue by rpetit3** [microbinfie-hackathon2020/CSIS#40]
Hello!

I wanted to submit a few edits to some of the markdowns? Where should these go? Direct to main, dev, or new patch?

Only asking because the dev and main branches are out of sync (main is ahead, and dev has ivar workflow). I can submit a PR to sort this out but wanted to check in first.

Thanks!

**Comment by rpetit3** [comment]
Ping @lskatz @boasvdp

**Comment by boasvdp** [comment]
Hey @rpetit3, thanks for reminding me. I've merged main into dev again. Could you have a look to see whether that makes sense and can you make your changes in dev? 

Afterwards I'll merge dev into main. Let me know whether this make sense!

**Comment by rpetit3** [comment]
Thank you, I'll take a look
